services:
  calc:
    build:
      context: ./calc
      dockerfile: Dockerfile
    container_name: calc
    expose:
      - "8080"
    env_file:
      - .env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - calc

